version: 2
updates:
  - package-ecosystem: pip
    versioning-strategy: increase-if-necessary
    directory: "/"
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
